# Generated by Django 4.1.7 on 2023-03-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phbook', '0002_alter_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='number',
            new_name='phone',
        ),
    ]
