# Generated by Django 4.1.7 on 2023-03-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phbook', '0003_rename_number_phone_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone',
            new_name='number',
        ),
    ]
