# Generated by Django 4.1.7 on 2023-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phbook', '0004_rename_phone_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
